import { Geist, Geist_Mono } from "next/font/google";
import { Roboto, Poppins, } from "next/font/google"; // ✅ Import Roboto & Poppins
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { ThemeProvider } from "@/context/ThemeContext";

import AuthProvider from "@/components/AuthProvider/AuthProvider";
 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Add Roboto
const roboto = Roboto({
  weight: ["400", "500", "700"], // You can customize available weights
  subsets: ["latin"],
  variable: "--font-roboto",
});

// ✅ Add Poppins
const poppins = Poppins({
  weight: ["400", "500", "700"], // Customize as needed
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${poppins.variable}`}
      >
         <ThemeProvider>
          <AuthProvider>
            <div className="containerr">
              <Navbar />
              {children}
              <Footer />
            </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
